//-----------------------------------------------------------------------------------------------------------------------
// This script is part of the Particle Universe Media Pack 1 product.
//
// Copyright (c) 2010 Henry van Merode
//
// Usage of this program is licensed under the terms of the Particle Universe Commercial License Media Pack 1.
// You can find a copy of the Commercial License in the Media Pack 1 package.
//-----------------------------------------------------------------------------------------------------------------------
system Hit/mp_hit_13
 {
    keep_local                                  true
    technique 
    {
        visual_particle_quota                   0
        material                                BaseWhite
        renderer                                Billboard
        {
        }
        emitter                                 Box 
        {
            emission_rate                       7
            angle                               0
            time_to_live                        2
            velocity                            0.0001
            emits                               technique_particle FlareTechnique
            force_emission                      true
            box_width                           30
            box_height                          30
            box_depth                           30
        }
        observer                                OnClear 
        {
            observe_particle_type               technique_particle
            handler                             DoStopSystem 
            {
            }
        }
    }
    technique FlareTechnique
    {
        visual_particle_quota                   50
        material                                mp_hit_glow_07
        default_particle_width                  60
        default_particle_height                 60
        default_particle_depth                  60
        renderer                                Billboard
        {
        }
        emitter                                 Point 
        {
            emission_rate                       3
            angle                               0
            time_to_live                        1
            velocity                            0.0001
            particle_width                      10
            particle_height                     dyn_random
            {
                min                             400
                max                             600
            }
            colour                              0.00784314 0.380392 0.835294 1
            force_emission                      true
        }
        emitter                                 Point 
        {
            emission_rate                       2
            angle                               0
            time_to_live                        1
            velocity                            0.0001
            force_emission                      true
        }
        affector                                Colour 
        {
            time_colour                         0    0 0 0 1
            time_colour                         0.2  1 1 1 1
            time_colour                         1    0 0 0 1
            colour_operation                    multiply
        }
    }
 }
