//-----------------------------------------------------------------------------------------------------------------------
// This script is part of the Particle Universe Media Pack 1 product.
//
// Copyright (c) 2010 Henry van Merode
//
// Usage of this program is licensed under the terms of the Particle Universe Commercial License Media Pack 1.
// You can find a copy of the Commercial License in the Media Pack 1 package.
//-----------------------------------------------------------------------------------------------------------------------
system Flare/mp_flare_04
 {
    keep_local                                  true
    technique 
    {
        visual_particle_quota                   100
        material                                mp_flare_elipses
        default_particle_width                  100
        default_particle_height                 100
        default_particle_depth                  100
        renderer                                Sphere
        {
        }
        emitter                                 Point 
        {
            emission_rate                       100
            angle                               0
            time_to_live                        dyn_random
            {
                min                             0.1
                max                             0.2
            }
            velocity                            0.0001
            colour                              0.721569 0.956863 0 1
        }
        affector                                Colour 
        {
            time_colour                         0    1 1 1 1
            time_colour                         1    0 0 0 1
            colour_operation                    multiply
        }
        affector                                GeometryRotator 
        {
            rotation_speed                      0
        }
    }
    technique 
    {
        material                                mp_spell_flare_02
        renderer                                Billboard
        {
            billboard_rotation_type             vertex
        }
        emitter                                 Point 
        {
            emission_rate                       40
            angle                               360
            time_to_live                        dyn_random
            {
                min                             0.2
                max                             0.4
            }
            velocity                            dyn_random
            {
                min                             50
                max                             150
            }
            all_particle_dimensions             dyn_random
            {
                min                             80
                max                             160
            }
            colour                              0 0 0 1
        }
        emitter                                 Box 
        {
            emission_rate                       7
            angle                               0
            time_to_live                        dyn_random
            {
                min                             1
                max                             2
            }
            velocity                            0.0001
            particle_width                      dyn_random
            {
                min                             5
                max                             10
            }
            particle_height                     dyn_random
            {
                min                             600
                max                             800
            }
            colour                              0 0 0 1
            box_width                           5
            box_height                          5
            box_depth                           5
        }
        affector                                Colour 
        {
            time_colour                         0    0 0 0 1
            time_colour                         0.2  0.913725 1 0.65098 1
            time_colour                         1    0 0 0 1
        }
    }
    technique 
    {
        material                                mp_flare_06
        renderer                                Billboard
        {
            billboard_type                      oriented_self
            billboard_origin                    top_center
            billboard_rotation_type             vertex
        }
        emitter                                 Point 
        {
            angle                               360
            time_to_live                        dyn_random
            {
                min                             1
                max                             2
            }
            velocity                            0.0001
            particle_width                      dyn_random
            {
                min                             5
                max                             10
            }
            particle_height                     dyn_random
            {
                min                             80
                max                             120
            }
            colour                              0.913725 1 0.65098 1
        }
        affector                                Colour 
        {
            time_colour                         0    0 0 0 1
            time_colour                         0.5  1 1 1 1
            time_colour                         1    0 0 0 1
            colour_operation                    multiply
        }
    }
 }
