system Flare/mp_diabolique
 {
    keep_local                                  true
    scale_velocity                              0.001
    scale                                       0.001 0.001 0.001
    technique 
    {
        material                                mp_flare_05
        renderer                                Billboard
        {
            billboard_type                      oriented_self
            billboard_rotation_type             vertex
        }
        emitter                                 SphereSurface Emitter1
        {
            emission_rate                       40
            angle                               0
            velocity                            0.001
            duration                            1
            particle_width                      dyn_random
            {
                min                             5
                max                             20
            }
            particle_height                     dyn_random
            {
                min                             1
                max                             10
            }
            colour                              0.956863 0.576471 0 1
            auto_direction                      true
            radius                              50
        }
        emitter                                 SphereSurface Emitter2
        {
            emission_rate                       40
            angle                               0
            velocity                            0.001
            duration                            1
            particle_width                      dyn_random
            {
                min                             5
                max                             20
            }
            particle_height                     dyn_random
            {
                min                             1
                max                             10
            }
            colour                              0.172549 0.396078 0.996078 1
            auto_direction                      true
            radius                              50
        }
        affector                                Vortex 
        {
            exclude_emitter                     Emitter1 
            rotation_axis                       -1 1 0
            rotation_speed                      2
        }
        affector                                Vortex 
        {
            exclude_emitter                     Emitter2 
            rotation_axis                       1 1 0
            rotation_speed                      2
        }
        affector                                Scale 
        {
            x_scale                             dyn_random
            {
                min                             10
                max                             40
            }
            y_scale                             dyn_random
            {
                min                             20
                max                             200
            }
        }
        affector                                Colour 
        {
            time_colour                         0    0 0 0 1
            time_colour                         0.5  1 1 1 1
            time_colour                         1    0 0 0 1
            colour_operation                    multiply
        }
        observer                                OnClear 
        {
            handler                             DoStopSystem 
            {
            }
        }
    }
 }
