system Flare/mp_sun
 {
    keep_local                                  true
    scale_velocity                              0.001
    scale                                       0.001 0.001 0.001
    technique 
    {
        visual_particle_quota                   5
        material                                mp_flare_sun
        default_particle_width                  300
        default_particle_height                 300
        renderer                                Billboard
        {
            billboard_rotation_type             vertex
        }
        emitter                                 Point 
        {
            emission_rate                       dyn_curved_linear
            {
                control_point                   0 50
                control_point                   0.1 2
            }
            time_to_live                        dyn_random
            {
                min                             1
                max                             2
            }
            velocity                            0.0001
        }
        affector                                Colour 
        {
            time_colour                         0    0 0 0 1
            time_colour                         0.5  1 1 1 1
            time_colour                         1    0 0 0 1
            colour_operation                    multiply
        }
    }
 }
