system Flare/mp_starfield
 {
    fast_forward                                10 1
    scale_velocity                              0.001
    scale                                       0.001 0.001 0.001
    technique 
    {
        visual_particle_quota                   2000
        emitted_emitter_quota                   500
        material                                mp_flare_star
        renderer                                Billboard
        {
            render_queue_group                  49
            texture_coords_rows                 2
            texture_coords_columns              2
        }
        emitter                                 SphereSurface 
        {
            emission_rate                       500
            time_to_live                        1000
            velocity                            0
            emits                               emitter_particle Point
            force_emission                      true
            radius                              50000
        }
        emitter                                 Point Point
        {
            emission_rate                       1
            time_to_live                        dyn_random
            {
                min                             1
                max                             5
            }
            velocity                            0
            all_particle_dimensions             dyn_random
            {
                min                             300
                max                             800
            }
            end_texture_coords_range            3
        }
        affector                                Colour 
        {
            time_colour                         0    0 0 0 1
            time_colour                         0.5  1 1 1 1
            time_colour                         1    0 0 0 1
            colour_operation                    multiply
        }
    }
 }
