system Flare/mp_flare_05
 {
    scale_velocity                              0.001
    scale                                       0.001 0.001 0.001
    technique 
    {
        visual_particle_quota                   40
        material                                mp_flare_07
        renderer                                Billboard
        {
            billboard_rotation_type             vertex
        }
        emitter                                 Point 
        {
            emission_rate                       dyn_curved_linear
            {
                control_point                   0 100
                control_point                   1 0
            }
            time_to_live                        dyn_random
            {
                min                             1
                max                             3
            }
            velocity                            0
            duration                            0.41
            particle_width                      dyn_random
            {
                min                             100
                max                             200
            }
            particle_height                     dyn_random
            {
                min                             200
                max                             500
            }
            colour                              0.992157 0.639216 0.376471 1
        }
        affector                                TextureRotator 
        {
            use_own_rotation                    true
            rotation                            dyn_random
            {
                min                             -4
                max                             4
            }
            rotation_speed                      dyn_random
            {
                min                             -3
                max                             3
            }
        }
        affector                                Colour 
        {
            time_colour                         0    0 0 0 1
            time_colour                         0.5  1 1 1 1
            time_colour                         1    0 0 0 1
            colour_operation                    multiply
        }
        observer                                OnClear 
        {
            enabled                             false
            handler                             DoStopSystem 
            {
            }
        }
    }
    technique 
    {
        visual_particle_quota                   50
        material                                mp_flare_elipse_02
        default_particle_width                  300
        default_particle_height                 300
        renderer                                Billboard
        {
            billboard_rotation_type             vertex
        }
        emitter                                 Point 
        {
            emission_rate                       120
            time_to_live                        dyn_random
            {
                min                             1
                max                             3
            }
            velocity                            0
            duration                            0.4
            colour                              0.713726 0.47451 1 1
        }
        affector                                TextureRotator 
        {
            use_own_rotation                    true
            rotation                            dyn_random
            {
                min                             -4
                max                             4
            }
            rotation_speed                      dyn_random
            {
                min                             -3
                max                             3
            }
        }
        affector                                Colour 
        {
            time_colour                         0    0 0 0 1
            time_colour                         0.5  1 1 1 1
            time_colour                         1    0 0 0 1
            colour_operation                    multiply
        }
    }
 }
