//-----------------------------------------------------------------------------------------------------------------------
// This script is part of the Particle Universe Media Pack 1 product.
//
// Copyright (c) 2010 Henry van Merode
//
// Usage of this program is licensed under the terms of the Particle Universe Commercial License Media Pack 1.
// You can find a copy of the Commercial License in the Media Pack 1 package.
//-----------------------------------------------------------------------------------------------------------------------
system Spell/mp_spell_effect_01
 {
    keep_local                                  true
    technique 
    {
        visual_particle_quota                   10
        material                                mp_spell_ring
        default_particle_width                  200
        default_particle_height                 200
        renderer                                Billboard
        {
            billboard_rotation_type             vertex
        }
        emitter                                 Point 
        {
            emission_rate                       4
            time_to_live                        dyn_random
            {
                min                             1
                max                             2
            }
            velocity                            0
            duration                            4
            colour                              0.643137 0.509804 1 1
        }
        affector                                Colour 
        {
            time_colour                         0    1 1 1 0
            time_colour                         0.5  1 1 1 0.1
            time_colour                         1    1 1 1 0
            colour_operation                    multiply
        }
        observer                                OnTime 
        {
            observe_until_event                 true
            handler                             DoStopSystem 
            {
            }
            since_start_system                  true
            on_time                             greater_than 6
        }
    }
    technique 
    {
        visual_particle_quota                   120
        material                                mp_spell_sweep
        default_particle_width                  200
        default_particle_height                 200
        renderer                                Billboard
        {
            billboard_type                      oriented_self
            billboard_origin                    bottom_center
            billboard_rotation_type             vertex
        }
        emitter                                 Point 
        {
            emission_rate                       40
            angle                               360
            time_to_live                        dyn_random
            {
                min                             1
                max                             2
            }
            velocity                            1
            duration                            3
            particle_width                      dyn_random
            {
                min                             10
                max                             30
            }
            particle_height                     dyn_random
            {
                min                             5
                max                             30
            }
            colour                              0.854902 0.8 1 1
        }
        affector                                Colour 
        {
            time_colour                         0    0 0 0 1
            time_colour                         0.5  0.3 0.3 0.3 1
            time_colour                         0.7  1 1 1 1
            time_colour                         1    0 0 0 1
            colour_operation                    multiply
        }
        affector                                Scale 
        {
            x_scale                             -20
            y_scale                             dyn_random
            {
                min                             100
                max                             200
            }
        }
    }
    technique 
    {
        visual_particle_quota                   20
        material                                mp_spell_flare_01
        renderer                                Billboard
        {
            billboard_rotation_type             vertex
        }
        emitter                                 Box 
        {
            angle                               360
            time_to_live                        dyn_random
            {
                min                             1
                max                             2
            }
            velocity                            dyn_random
            {
                min                             1
                max                             5
            }
            duration                            4
            all_particle_dimensions             dyn_random
            {
                min                             30
                max                             100
            }
            colour                              0.643137 0.509804 1 1
            box_width                           30
            box_height                          30
            box_depth                           30
        }
        affector                                Colour 
        {
            time_colour                         0    0 0 0 1
            time_colour                         0.5  1 1 1 1
            time_colour                         1    0 0 0 1
            colour_operation                    multiply
        }
    }
 }
