//-----------------------------------------------------------------------------------------------------------------------
// This script is part of the Particle Universe Media Pack 1 product.
//
// Copyright (c) 2010 Henry van Merode
//
// Usage of this program is licensed under the terms of the Particle Universe Commercial License Media Pack 1.
// You can find a copy of the Commercial License in the Media Pack 1 package.
//-----------------------------------------------------------------------------------------------------------------------
system Smoke/mp_smoke_bash
{
    scale_velocity                              0.001
    scale                                       0.001 0.001 0.001
    technique 
    {
        visual_particle_quota                   100
        material                                mp_smoke_chimney
        renderer                                Billboard
        {
            billboard_rotation_type             vertex
        }
        emitter                                 Circle Core
        {
            emission_rate                       400
            angle                               0
            time_to_live                        dyn_random
            {
                min                             0.5
                max                             1.2
            }
            velocity                            dyn_random
            {
                min                             500
                max                             600
            }
            all_particle_dimensions             dyn_random
            {
                min                             100
                max                             200
            }
            colour                              0 0 0 1
            auto_direction                      true
            force_emission                      true
            radius                              0.1
        }
        affector                                ScaleVelocity 
        {
            velocity_scale                      dyn_curved_linear
            {
                control_point                   0 -1500
                control_point                   0.5 -100
                control_point                   1 50
            }
        }
        affector                                Scale 
        {
            xyz_scale                           -50
        }
        affector                                Colour 
        {
            time_colour                         0    0 0 0 1
            time_colour                         0.5  0.2 0.2 0.2 1
            time_colour                         1    0 0 0 1
        }
        affector                                LinearForce 
        {
            force_vector                        0 150 0
        }
        affector                                TextureRotator 
        {
            use_own_rotation                    true
            rotation                            dyn_random
            {
                min                             -3
                max                             3
            }
            rotation_speed                      dyn_random
            {
                min                             -2
                max                             2
            }
        }
        observer                                OnClear 
        {
            handler                             DoStopSystem 
            {
            }
        }
    }
 }
