//-----------------------------------------------------------------------------------------------------------------------
// This script is part of the Particle Universe Media Pack 1 product.
//
// Copyright (c) 2010 Henry van Merode
//
// Usage of this program is licensed under the terms of the Particle Universe Commercial License Media Pack 1.
// You can find a copy of the Commercial License in the Media Pack 1 package.
//-----------------------------------------------------------------------------------------------------------------------
system Nature/mp_rain
 {
    fast_forward                                1 1
    technique 
    {
        visual_particle_quota                   1000
        material                                mp_nature_rain
        default_particle_width                  2
        default_particle_height                 100
        renderer                                Billboard
        {
            texture_coords_rows                 3
            texture_coords_columns              3
            billboard_type                      oriented_self
            billboard_origin                    top_center
        }
        emitter                                 Box 
        {
            emission_rate                       1000
            angle                               2
            time_to_live                        1
            velocity                            2500
            position                            0 500 0
            direction                           0.2 -1 0
            end_texture_coords_range            7
            box_width                           1000
            box_height                          1
            box_depth                           1000
        }
    }
 }
