//-----------------------------------------------------------------------------------------------------------------------
// This script is part of the Particle Universe Media Pack 1 product.
//
// Copyright (c) 2010 Henry van Merode
//
// Usage of this program is licensed under the terms of the Particle Universe Commercial License Media Pack 1.
// You can find a copy of the Commercial License in the Media Pack 1 package.
//-----------------------------------------------------------------------------------------------------------------------
system Woosh/mp_woosh_05
 {
    keep_local                                  true
    technique 
    {
        position                                0 -200 0
        visual_particle_quota                   1
        material                                mp_woosh_circle_03
        renderer                                Billboard
        {
            billboard_type                      perpendicular_self
            billboard_rotation_type             vertex
            common_direction                    0 1 0
            common_up_vector                    0 0 1
        }
        emitter                                 Point 
        {
            emission_rate                       1
            angle                               0
            time_to_live                        0.4
            velocity                            0.0001
            colour                              1 0.533333 0.0666667 1
            force_emission                      true
        }
        affector                                Colour 
        {
            time_colour                         0    0 0 0 1
            time_colour                         0.4  1 1 1 1
            time_colour                         0.5  1 1 1 1
            time_colour                         1    0 0 0 1
            colour_operation                    multiply
        }
        affector                                Scale 
        {
            xyz_scale                           3000
        }
        affector                                TextureRotator 
        {
            rotation                            dyn_random
            {
                min                             -3
                max                             3
            }
            rotation_speed                      0
        }
        observer                                OnClear 
        {
            handler                             DoStopSystem 
            {
            }
        }
    }
 }
