system Woosh/mp_woosh_11
 {
    scale_velocity                              0.001
    scale                                       0.001 0.001 0.001
    technique 
    {
        position                                0 -200 -200
        visual_particle_quota                   10
        material                                mp_woosh_circle_07
        renderer                                Billboard
        {
            billboard_type                      perpendicular_self
            billboard_rotation_type             vertex
            common_direction                    0 1 0
            common_up_vector                    0 0 1
        }
        emitter                                 Point 
        {
            emission_rate                       20
            angle                               0
            time_to_live                        dyn_random
            {
                min                             0.4
                max                             0.5
            }
            velocity                            0.0001
            duration                            0.2
            colour                              0.623529 0.235294 0.835294 1
        }
        emitter                                 Point 
        {
            emission_rate                       20
            angle                               0
            time_to_live                        dyn_random
            {
                min                             0.4
                max                             0.5
            }
            velocity                            0.0001
            duration                            0.2
            colour                              0.878431 0.188235 0.396078 1
        }
        affector                                Colour 
        {
            time_colour                         0    0 0 0 1
            time_colour                         0.4  1 1 1 1
            time_colour                         0.5  1 1 1 1
            time_colour                         1    0 0 0 1
            colour_operation                    multiply
        }
        affector                                Scale 
        {
            xyz_scale                           3000
        }
        affector                                TextureRotator 
        {
            rotation                            dyn_random
            {
                min                             -3
                max                             3
            }
            rotation_speed                      0
        }
    }
    technique 
    {
        position                                0 -200 0
        material                                mp_woosh_glow_01
        renderer                                Billboard
        {
        }
        emitter                                 Point 
        {
            emission_rate                       dyn_curved_linear
            {
                control_point                   0 500
                control_point                   0.3 0
            }
            angle                               10
            time_to_live                        1
            velocity                            dyn_random
            {
                min                             400
                max                             800
            }
            duration                            1
            all_particle_dimensions             dyn_random
            {
                min                             30
                max                             100
            }
            colour                              0.792157 0.247059 0.929412 1
        }
        affector                                LinearForce 
        {
            force_vector                        0 -1000 0
        }
        affector                                Colour 
        {
            time_colour                         0    0 0 0 1
            time_colour                         0.5  1 1 1 1
            time_colour                         1    0 0 0 1
            colour_operation                    multiply
        }
    }
 }
