system Woosh/mp_woosh_07
 {
    keep_local                                  true
    scale_velocity                              0.001
    scale                                       0.001 0.001 0.001
    technique 
    {
        position                                0 -200 -150
        visual_particle_quota                   130
        material                                mp_woosh_streak_01
        renderer                                Billboard
        {
            billboard_type                      perpendicular_self
            billboard_rotation_type             vertex
            common_direction                    0 1 0
            common_up_vector                    0 0 1
        }
        emitter                                 Point Core
        {
            emission_rate                       100
            angle                               0
            time_to_live                        dyn_random
            {
                min                             0.4
                max                             1
            }
            velocity                            0.0001
            duration                            0.5
            particle_width                      dyn_random
            {
                min                             100
                max                             300
            }
            particle_height                     dyn_random
            {
                min                             1
                max                             100
            }
            colour                              0.454902 0.937255 0.780392 1
            force_emission                      true
        }
        emitter                                 Point Core
        {
            emission_rate                       20
            angle                               0
            time_to_live                        dyn_random
            {
                min                             0.4
                max                             1
            }
            velocity                            0.0001
            duration                            1
            particle_width                      100
            particle_height                     200
            colour                              0.454902 0.937255 0.780392 1
            force_emission                      true
        }
        affector                                TextureRotator 
        {
            use_own_rotation                    true
            rotation                            dyn_random
            {
                min                             -4
                max                             4
            }
            rotation_speed                      0
        }
        affector                                Colour 
        {
            time_colour                         0    0 0 0 1
            time_colour                         0.5  1 1 1 1
            time_colour                         1    0 0 0 1
            colour_operation                    multiply
        }
        affector                                Scale 
        {
            x_scale                             -200
            y_scale                             dyn_random
            {
                min                             100
                max                             1000
            }
        }
        observer                                OnClear 
        {
            handler                             DoStopSystem 
            {
            }
        }
    }
 }
