//-----------------------------------------------------------------------------------------------------------------------
// This script is part of the Particle Universe Media Pack 1 product.
//
// Copyright (c) 2010 Henry van Merode
//
// Usage of this program is licensed under the terms of the Particle Universe Commercial License Media Pack 1.
// You can find a copy of the Commercial License in the Media Pack 1 package.
//-----------------------------------------------------------------------------------------------------------------------
system Weapon/mp_bullettrail_05
{
    technique 
    {
        visual_particle_quota                   10
        material                                mp_weapon_flare_green
        default_particle_width                  100
        default_particle_height                 100
        renderer                                Billboard
        {
            billboard_rotation_type             vertex
        }
        emitter                                 Point 
        {
            emission_rate                       1
            angle                               0
            velocity                            5000
            direction                           0 0 -1
            force_emission                      true
        }
        affector                                TextureRotator 
        {
        }
        observer                                OnClear 
        {
            handler                             DoStopSystem 
            {
            }
        }
    }
}
