//-----------------------------------------------------------------------------------------------------------------------
// This script is part of the Particle Universe Media Pack 1 product.
//
// Copyright (c) 2010 Henry van Merode
//
// Usage of this program is licensed under the terms of the Particle Universe Commercial License Media Pack 1.
// You can find a copy of the Commercial License in the Media Pack 1 package.
//-----------------------------------------------------------------------------------------------------------------------
system Weapon/mp_muzzle_02
{
    technique 
    {
        visual_particle_quota                   8
        material                                mp_weapon_muzzle_02
        default_particle_width                  300
        default_particle_height                 300
        renderer                                Billboard
        {
            texture_coords_rows                 2
            texture_coords_columns              2
        }
        emitter                                 Point 
        {
            emission_rate                       3
            angle                               0
            time_to_live                        dyn_random
            {
                min                             0.1
                max                             0.2
            }
            velocity                            1e-006
            direction                           1 1 0
            end_texture_coords_range            3
            force_emission                      true
        }
        affector                                Colour 
        {
            time_colour                         0    1 1 1 1
            time_colour                         1    0 0 0 0
            colour_operation                    multiply
        }
        affector                                Scale 
        {
            xyz_scale                           1000
        }
        observer                                OnClear 
        {
            handler                             DoStopSystem 
            {
            }
        }
    }
}
