//-----------------------------------------------------------------------------------------------------------------------
// This script is part of the Particle Universe Media Pack 1 product.
//
// Copyright (c) 2010 Henry van Merode
//
// Usage of this program is licensed under the terms of the Particle Universe Commercial License Media Pack 1.
// You can find a copy of the Commercial License in the Media Pack 1 package.
//-----------------------------------------------------------------------------------------------------------------------
system Weapon/mp_rocket
{
    keep_local                                  true
    technique 
    {
        visual_particle_quota                   30
        material                                mp_weapon_rocket_01_1x4
        renderer                                Billboard
        {
            texture_coords_columns              4
            billboard_type                      oriented_self
            billboard_origin                    bottom_center
            billboard_rotation_type             vertex
        }
        emitter                                 Point 
        {
            emission_rate                       300
            angle                               0
            time_to_live                        dyn_random
            {
                min                             0.1
                max                             0.2
            }
            velocity                            1
            particle_width                      50
            particle_height                     100
            direction                           0 -1 0
            end_texture_coords_range            3
        }
        affector                                Scale 
        {
            x_scale                             -100
            y_scale                             2000
        }
        affector                                Colour 
        {
            time_colour                         0    1 1 1 0
            time_colour                         0.2  1 1 1 0
            time_colour                         0.8  1 1 1 0.5
            time_colour                         1    1 1 1 0
            colour_operation                    multiply
        }
    }
    technique 
    {
        visual_particle_quota                   20
        material                                mp_weapon_rocket_02_1x4
        renderer                                Billboard
        {
            texture_coords_columns              4
            billboard_type                      oriented_self
            billboard_origin                    bottom_center
            billboard_rotation_type             vertex
        }
        emitter                                 Point 
        {
            emission_rate                       200
            angle                               0
            time_to_live                        dyn_random
            {
                min                             0.1
                max                             0.2
            }
            velocity                            1
            particle_width                      50
            particle_height                     50
            direction                           0 -1 0
            end_texture_coords_range            3
        }
        affector                                Scale 
        {
            x_scale                             -200
            y_scale                             2000
        }
        affector                                Colour 
        {
            time_colour                         0    0 0 0 1
            time_colour                         0.2  0 0 0 1
            time_colour                         0.8  0.3 0.3 0.3 1
            time_colour                         1    0 0 0 1
            colour_operation                    multiply
        }
    }
    technique 
    {
        visual_particle_quota                   40
        material                                mp_weapon_rocketboost
        renderer                                Billboard
        {
            texture_coords_rows                 0
            texture_coords_columns              0
            billboard_type                      oriented_self
            billboard_origin                    bottom_center
            billboard_rotation_type             vertex
        }
        emitter                                 Point 
        {
            emission_rate                       300
            angle                               0
            time_to_live                        dyn_random
            {
                min                             0.1
                max                             0.2
            }
            velocity                            1
            particle_width                      dyn_random
            {
                min                             5
                max                             25
            }
            particle_height                     dyn_random
            {
                min                             25
                max                             75
            }
            direction                           0 -1 0
        }
        affector                                Scale 
        {
            x_scale                             -200
            y_scale                             1000
        }
        affector                                Colour 
        {
            time_colour                         0    1 1 1 1
            time_colour                         0.8  1 1 1 1
            time_colour                         1    0 0 0 1
            colour_operation                    multiply
        }
    }
    technique 
    {
        position                                0 -10 0
        visual_particle_quota                   5
        material                                mp_weapon_rocketflare
        default_particle_width                  300
        default_particle_height                 300
        renderer                                Billboard
        {
            billboard_rotation_type             vertex
        }
        emitter                                 Point 
        {
            emission_rate                       dyn_curved_linear
            {
                control_point                   0 50
                control_point                   0.1 2
            }
            time_to_live                        dyn_random
            {
                min                             1
                max                             2
            }
            velocity                            0.0001
        }
        affector                                Colour 
        {
            time_colour                         0    0 0 0 1
            time_colour                         0.5  1 1 1 1
            time_colour                         1    0 0 0 1
            colour_operation                    multiply
        }
    }
}
