//-----------------------------------------------------------------------------------------------------------------------
// This script is part of the Particle Universe Media Pack 1 product.
//
// Copyright (c) 2010 Henry van Merode
//
// Usage of this program is licensed under the terms of the Particle Universe Commercial License Media Pack 1.
// You can find a copy of the Commercial License in the Media Pack 1 package.
//-----------------------------------------------------------------------------------------------------------------------
system Hit/mp_hit_02
{
    keep_local                                  true
    scale_velocity                              0.001
    scale                                       0.001 0.001 0.001
    technique 
    {
        visual_particle_quota                   65
        material                                mp_hit_arrow
        renderer                                Billboard
        {
            billboard_type                      oriented_self
            billboard_rotation_type             vertex
        }
        emitter                                 Point 
        {
            emission_rate                       60
            angle                               360
            time_to_live                        0.2
            velocity                            1e-006
            duration                            0.1
            particle_width                      dyn_random
            {
                min                             60
                max                             200
            }
            particle_height                     dyn_random
            {
                min                             100
                max                             400
            }
            colour                              0.984314 0.92549 0.509804 1
            force_emission                      true
        }
        affector                                Colour 
        {
            time_colour                         0    0 0 0 1
            time_colour                         0.5  1 1 1 1
            time_colour                         1    0 0 0 1
            colour_operation                    multiply
        }
        affector                                Scale 
        {
            y_scale                             dyn_random
            {
                min                             200
                max                             1000
            }
        }
        observer                                OnTime 
        {
            observe_until_event                 true
            handler                             DoStopSystem 
            {
            }
            since_start_system                  true
            on_time                             greater_than 1
        }
    }
    technique 
    {
        visual_particle_quota                   1
        material                                mp_hit_circle_01
        renderer                                Billboard
        {
        }
        emitter                                 Point 
        {
            emission_rate                       1
            angle                               0
            time_to_live                        0.2
            velocity                            0
            duration                            0.1
            colour                              0.992157 0.956863 0.72549 1
            force_emission                      true
        }
        affector                                Colour 
        {
            time_colour                         0    0 0 0 1
            time_colour                         0.5  1 1 1 1
            time_colour                         1    0 0 0 1
            colour_operation                    multiply
        }
        affector                                Scale 
        {
            xyz_scale                           2000
        }
    }
 }
